name: CS300
services:
  cloud:
    image: nginx
    networks:
      - cloud_proxy_net
    cap_add:
      - NET_ADMIN
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./logs/cloud:/var/log/nginx

  proxy:
    build: ./proxy
    networks:
      - cloud_proxy_net
      - proxy_gateways_net
    cap_add:
      - NET_ADMIN
    ports:
      - "9090:9090"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./logs/proxy:/var/log/nginx
      - ./config:/app/config

  gateway1:
    build: ./gateway
    networks:
      - proxy_gateways_net
      - gateway1_mobiles_net
    cap_add:
      - NET_ADMIN
    ports:
      - "9091:9090"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./logs/edge1:/app/logs
      - ./config:/app/config

  gateway2:
    build: ./gateway
    networks:
      - proxy_gateways_net
      - gateway2_mobiles_net
    cap_add:
      - NET_ADMIN
    ports:
      - "9092:9090"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./logs/edge2:/app/logs
      - ./config:/app/config

  mobile1_1:
    build: ./mobile
    networks:
      - gateway1_mobiles_net
    environment:
      - GATEWAY=gateway1
    cap_add:
      - NET_ADMIN
    ports:
      - "9093:9090"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./logs/mobile1_1:/app/logs
      - ./config:/app/config

  mobile1_2:
    build: ./mobile
    networks:
      - gateway1_mobiles_net
    environment:
      - GATEWAY=gateway1
    cap_add:
      - NET_ADMIN

  mobile1_3:
    build: ./mobile
    networks:
      - gateway1_mobiles_net
    environment:
      - GATEWAY=gateway1
    cap_add:
      - NET_ADMIN

  mobile1_4:
    build: ./mobile
    networks:
      - gateway1_mobiles_net
    environment:
      - GATEWAY=gateway1
    cap_add:
      - NET_ADMIN

  mobile2_1:
    build: ./mobile
    networks:
      - gateway2_mobiles_net
    environment:
      - GATEWAY=gateway2
    cap_add:
      - NET_ADMIN

  mobile2_2:
    build: ./mobile
    networks:
      - gateway2_mobiles_net
    environment:
      - GATEWAY=gateway2
    cap_add:
      - NET_ADMIN

  mobile2_3:
    build: ./mobile
    networks:
      - gateway2_mobiles_net
    environment:
      - GATEWAY=gateway2
    cap_add:
      - NET_ADMIN

  mobile2_4:
    build: ./mobile
    networks:
      - gateway2_mobiles_net
    environment:
      - GATEWAY=gateway2
    cap_add:
      - NET_ADMIN

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9095:9090"
    networks:
      - monitoring_net
      - cloud_proxy_net
      - proxy_gateways_net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./config/grafana.yml:/etc/grafana/grafana.ini
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring_net
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  cloud_proxy_net:
  proxy_gateways_net:
  gateway1_mobiles_net:
  gateway2_mobiles_net:
  monitoring_net:

volumes:
  prometheus_data:
  grafana_data: