name: CS300
services:
  cloud:
    image: nginx
    networks:
      - cloud_proxy_net
    cap_add:
      - NET_ADMIN

  proxy:
    build: ./proxy
    networks:
      - cloud_proxy_net
      - proxy_gateways_net
    cap_add:
      - NET_ADMIN

  gateway1:
    build: ./gateway
    networks:
      - proxy_gateways_net
      - gateway1_mobiles_net
    cap_add:
      - NET_ADMIN

  gateway2:
    build: ./gateway
    networks:
      - proxy_gateways_net
      - gateway2_mobiles_net
    cap_add:
      - NET_ADMIN

  mobile1_1:
    build: ./mobile
    networks:
      - gateway1_mobiles_net
    environment:
      - GATEWAY=gateway1
    cap_add:
      - NET_ADMIN

  mobile1_2:
    build: ./mobile
    networks:
      - gateway1_mobiles_net
    environment:
      - GATEWAY=gateway1
    cap_add:
      - NET_ADMIN

  mobile1_3:
    build: ./mobile
    networks:
      - gateway1_mobiles_net
    environment:
      - GATEWAY=gateway1
    cap_add:
      - NET_ADMIN

  mobile1_4:
    build: ./mobile
    networks:
      - gateway1_mobiles_net
    environment:
      - GATEWAY=gateway1
    cap_add:
      - NET_ADMIN

  mobile2_1:
    build: ./mobile
    networks:
      - gateway2_mobiles_net
    environment:
      - GATEWAY=gateway2
    cap_add:
      - NET_ADMIN

  mobile2_2:
    build: ./mobile
    networks:
      - gateway2_mobiles_net
    environment:
      - GATEWAY=gateway2
    cap_add:
      - NET_ADMIN

  mobile2_3:
    build: ./mobile
    networks:
      - gateway2_mobiles_net
    environment:
      - GATEWAY=gateway2
    cap_add:
      - NET_ADMIN

  mobile2_4:
    build: ./mobile
    networks:
      - gateway2_mobiles_net
    environment:
      - GATEWAY=gateway2
    cap_add:
      - NET_ADMIN

networks:
  cloud_proxy_net:
  proxy_gateways_net:
  gateway1_mobiles_net:
  gateway2_mobiles_net: