name: CS300-test

services:
  cloud:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_TYPE=CLOUD
      - PLACEMENT_STRATEGY=${PLACEMENT_STRATEGY:-GVMP}
      - CONFIG_NAME=${CONFIG_NAME:-Config-1}
      - PORT=8080
    volumes:
      - ./config:/app/config
      - ./logs/cloud:/app/logs
    networks:
      - fog-network

  proxy:
    build: .
    ports:
      - "8081:8080"
    environment:
      - NODE_TYPE=PROXY
      - PARENT_HOST=cloud
      - PARENT_PORT=8080
      - PLACEMENT_STRATEGY=${PLACEMENT_STRATEGY:-GVMP}
      - CONFIG_NAME=${CONFIG_NAME:-Config-1}
      - PORT=8080
    volumes:
      - ./config:/app/config
      - ./logs/proxy:/app/logs
    depends_on:
      - cloud
    networks:
      - fog-network

  edge1:
    build: .
    ports:
      - "8082:8080"
    environment:
      - NODE_TYPE=EDGE
      - NODE_ID=1
      - PARENT_HOST=proxy
      - PARENT_PORT=8080
      - PLACEMENT_STRATEGY=${PLACEMENT_STRATEGY:-GVMP}
      - CONFIG_NAME=${CONFIG_NAME:-Config-1}
      - PORT=8080
    volumes:
      - ./config:/app/config
      - ./logs/edge1:/app/logs
    depends_on:
      - proxy
    networks:
      - fog-network

  edge2:
    build: .
    ports:
      - "8083:8080"
    environment:
      - NODE_TYPE=EDGE
      - NODE_ID=2
      - PARENT_HOST=proxy
      - PARENT_PORT=8080
      - PLACEMENT_STRATEGY=${PLACEMENT_STRATEGY:-GVMP}
      - CONFIG_NAME=${CONFIG_NAME:-Config-1}
      - PORT=8080
    volumes:
      - ./config:/app/config
      - ./logs/edge2:/app/logs
    depends_on:
      - proxy
    networks:
      - fog-network

networks:
  fog-network:
    driver: bridge