apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"

dashboards:
  - name: EEG Monitoring
    editable: true
    panels:
      - title: "EEG Data Processing Rate"
        type: graph
        datasource: Prometheus
        targets:
          - expr: rate(eeg_data_processed_total[5m])
      - title: "Gateway Request Latency"
        type: graph
        datasource: Prometheus
        targets:
          - expr: gateway_request_latency_seconds
      - title: "Gateway Request Failures"
        type: graph
        datasource: Prometheus
        targets:
          - expr: gateway_request_failures_total
