version: 1

formatters:
  standard:
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
  json:
    format: "%(asctime)s %(name)s %(levelname)s %(message)s"
    class: pythonjsonlogger.jsonlogger.JsonFormatter

handlers:
  console:
    class: logging.StreamHandler
    formatter: standard
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    formatter: json
    filename: /logs/%(container_name)s/app.log
    maxBytes: 10485760 # 10MB
    backupCount: 5

loggers:
  mobile:
    level: INFO
    handlers: [console, file]
    propagate: false

  gateway:
    level: INFO
    handlers: [console, file]
    propagate: false

  proxy:
    level: INFO
    handlers: [console, file]
    propagate: false

root:
  level: INFO
  handlers: [console]
