global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: mobile
    static_configs:
      - targets:
          - mobile1_1:9090
          - mobile1_2:9090
          - mobile1_3:9090
          - mobile1_4:9090
          - mobile2_1:9090
          - mobile2_2:9090
          - mobile2_3:9090
          - mobile2_4:9090

  - job_name: gateway
    static_configs:
      - targets:
          - gateway1:8000
          - gateway2:8000