global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "mobile"
    static_configs:
      - targets: ["mobile:9090"]
    metrics_path: /metrics

  - job_name: "gateway"
    static_configs:
      - targets: ["gateway:9090"]
    metrics_path: /metrics
