global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "mobile1_1"
    static_configs:
      - targets: ["mobile1_1:9090"]
    metrics_path: /metrics

  - job_name: "mobile1_2"
    static_configs:
      - targets: ["mobile1_2:9090"]

  - job_name: "gateway1"
    static_configs:
      - targets: ["gateway1:8000"]
    metrics_path: /metrics

  - job_name: "gateway2"
    static_configs:
      - targets: ["gateway2:8000"]
    metrics_path: /metrics
