apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy # Use Grafana backend as proxy
    url: http://loki:3100 # Internal URL Grafana uses to reach Loki
    jsonData:
      # Optional: Set derived fields for better linking from logs to traces/metrics
      # derivedFields:
      #   - datasourceUid: 'PBFA97CFB590B2093' # UID of your Prometheus datasource
      #     matcherRegex: 'traceID=(\w+)'
      #     name: 'TraceID'
      #     url: '/explore?orgId=1&left=["now-1h","now","Tempo",{"query":"$${__value.raw}"}]'
      #     urlDisplayLabel: 'View Trace'
      maxLines: 1000
    version: 1
    editable: true
    isDefault: false # Keep Prometheus as default for now